---
abstract: unknown
author:
  - unknown
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.66, CPAN::Meta::Converter version 2.120921'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Sort-MultipleFields
no_index:
  directory:
    - t
    - inc
requires:
  Scalar::Util: 0
  Test::More: 0
resources:
  bugtracker: https://github.com/DrHyde/perl-modules-Sort-MultipleFields/issues
  repository: https://github.com/DrHyde/perl-modules-Sort-MultipleFields
version: 1.01
