# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Sort-MultipleFields
version:      1.0
version_from: lib/Sort/MultipleFields.pm
installdirs:  site
requires:
    Scalar::Util:                  0
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
